### ISSUE TITLE
unable to recieve email after using this module .

### ISSUE THREAD

**Issue by samairali** [magespecialist/m2-MSP_SMTP#1]
Unable to receive email even i am not receiving email in spam . no code error nothing everything is fine but still not working . i am using magento 2.2.6 . is it compatible with it ?

**Comment by giacmir** [comment]
Hi @samairali 
we haven't tested it with 2.2.6 yet, but we have several projects up to 2.2.5 using it.

Have you tried to activate the debug mode? Look at var/log/smtp.log, is there something useful in that file?

**Comment by samairali** [comment]
http://prntscr.com/l0a4dp
here is the screenshot please check if you got something . after installing the module we get some view on admin ? i just installed the module .
