### ISSUE TITLE
Body mail unrecognized

### ISSUE THREAD

**Issue by lucafuse94** [magespecialist/m2-MSP_SMTP#12]
### **Preconditions (*)**
Magento 2.3.4
PHP 7.2
SMTP 3.0.1
### **Steps to reproduce (*)**
Place an order
### **Expected result (*)**
All Email Send (order, invoice, etc...)
### **Actual result (*)**
```
Body mail unrecognized
```

**Comment by francescosalvi** [comment]
@lucafuse94 I think [this PR](https://github.com/magespecialist/m2-MSP_SMTP/pull/13) solves the issue?

**Comment by lucafuse94** [comment]
@francescosalvi yes. thank you
