### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function getParts() on string

### ISSUE THREAD

**Issue by erfanimani** [magespecialist/m2-MSP_SMTP#3]
Clean Magento 2.3.0 install. Every email sent from the admin fails. (i.e. forgot password, or when you create a new admin user in the backend).

Fatal error: Uncaught Error: Call to a member function getParts() on string in vendor/msp/smtp/Mail/Transport.php:131

    #0 vendor/msp/smtp/Mail/Transport.php(59): MSP\SMTP\Mail\Transport->setContent() 
    #1 vendor/magento/framework/Interception/Interceptor.php(58): MSP\SMTP\Mail\Transport->sendMessage() 
    #2 vendor/magento/framework/Interception/Interceptor.php(138): MSP\SMTP\Mail\Transport\Interceptor->___callParent('sendMessage', Array) 
    #3 vendor/magento/module-email/Model/Mail/TransportInterfacePlugin.php(48): MSP\SMTP\Mail\Transport\Interceptor->Magento\Framework\Interception\{closure}() 
    #4 vendor/magento/framework/Interception/Interceptor.php(135): Magento\Email\Model\Mail\TransportInterfacePlugin->aroundSendMessage(Object(MSP\SMTP\Mail\Transport\Interceptor), Object(Closure)) 
    #5 vendor/magento/framework/Interce in /srv/releases/20190205162043/vendor/msp/smtp/Mail/Transport.php on line 131

**Comment by Mikito-San** [comment]
Fixed on 2.3.6
